import app from './visual-final.js';

const PREMIUM_V5 = `
<style>
/* ROAD TO PEACE PRIDE — premium v5 layered artwork */
body.rpp-gate-active .wrap{width:100%!important;max-width:none!important;margin:0!important;padding:0!important}
#gate:not(.hidden){display:grid!important;place-items:center!important;min-height:100svh!important;padding:0!important;background:radial-gradient(circle at 50% 46%,#102858 0%,#06162f 35%,#020817 72%,#01040a 100%)!important;overflow:hidden!important}
#gate .gate-card{position:relative!important;isolation:isolate!important;overflow:hidden!important;background:#020817!important}
#gate .gate-card.orn:before{content:""!important;display:block!important;position:absolute!important;inset:0!important;z-index:0!important;background:url('/assets/premium-v5-bg.webp?v=5') center/100% 100% no-repeat!important;opacity:1!important;filter:saturate(1.06) contrast(1.035)!important;pointer-events:none!important;animation:rppArtworkBreath 14s ease-in-out infinite!important;transform-origin:50% 55%!important}
#gate .gate-card.orn:after{content:""!important;display:block!important;position:absolute!important;inset:0!important;z-index:1!important;background:linear-gradient(180deg,rgba(0,5,16,.22) 0%,rgba(0,5,16,.04) 29%,rgba(0,4,14,.02) 52%,rgba(0,5,18,.18) 61%,rgba(0,5,18,.76) 100%),radial-gradient(ellipse at 50% 53%,transparent 38%,rgba(0,0,0,.18) 74%,rgba(0,0,0,.42) 100%)!important;border:0!important;box-shadow:none!important;pointer-events:none!important}
.rpp-v5-frame{position:absolute;z-index:4;inset:1.15%;pointer-events:none;border:1px solid rgba(247,207,105,.96);box-shadow:inset 0 0 0 1px rgba(130,78,13,.92),inset 0 0 0 4px rgba(240,184,64,.17),0 0 10px rgba(231,180,65,.12)}
.rpp-v5-frame:before{content:"";position:absolute;inset:1.25%;border:1px solid rgba(219,158,48,.72);box-shadow:inset 0 0 0 1px rgba(255,232,155,.10)}
.rpp-v5-frame:after{content:"";position:absolute;left:7%;right:7%;top:1.5%;height:1px;background:linear-gradient(90deg,transparent,#b9761b 8%,#ffe49a 50%,#b9761b 92%,transparent);box-shadow:0 0 9px rgba(255,215,118,.22)}
.rpp-v5-corner{position:absolute;width:8.5%;aspect-ratio:1;z-index:5;pointer-events:none;opacity:.96}
.rpp-v5-corner:before,.rpp-v5-corner:after{content:"";position:absolute;inset:0;border-style:solid;border-color:#d79a35}
.rpp-v5-corner:before{border-width:1px 0 0 1px}.rpp-v5-corner:after{inset:18%;border-width:1px 0 0 1px;border-color:#f1ca70}
.rpp-v5-corner.tl{left:2.5%;top:2.5%}.rpp-v5-corner.tr{right:2.5%;top:2.5%;transform:rotate(90deg)}.rpp-v5-corner.br{right:2.5%;bottom:2.5%;transform:rotate(180deg)}.rpp-v5-corner.bl{left:2.5%;bottom:2.5%;transform:rotate(270deg)}
#rppCrispCopy{position:absolute!important;inset:0!important;z-index:8!important;left:0!important;right:0!important;top:0!important;text-align:center!important;pointer-events:none!important;text-shadow:0 3px 18px rgba(0,0,0,.7)!important}
#rppCrispCopy .private{display:none!important}
#rppCrispCopy .collection{position:absolute!important;top:5.35%!important;left:7%!important;right:7%!important;margin:0!important;color:#e7c26a!important;font:600 clamp(8px,2.25vw,12px)/1.25 Georgia,'Times New Roman',serif!important;letter-spacing:.27em!important;text-shadow:0 1px 8px #000,0 0 10px rgba(234,184,72,.2)!important}
#rppCrispCopy .title{position:absolute!important;top:11.9%!important;left:4.8%!important;right:4.8%!important;margin:0!important;white-space:nowrap!important;line-height:1!important;overflow:visible!important}
#rppCrispCopy .rpp-road{display:block!important;margin-bottom:1.8%!important;color:#f0d487!important;font:500 clamp(18px,5.7vw,28px)/1.05 Georgia,'Times New Roman',serif!important;letter-spacing:.15em!important;text-shadow:0 2px 14px rgba(0,0,0,.9),0 0 15px rgba(228,175,54,.14)!important}
#rppCrispCopy .rpp-pride{display:block!important;font:500 clamp(42px,12vw,54px)/.96 Georgia,'Times New Roman',serif!important;letter-spacing:.012em!important;background:linear-gradient(180deg,#fff0b1 0%,#f0c45e 34%,#b8751c 61%,#f1c967 82%,#9a5b12 100%)!important;-webkit-background-clip:text!important;background-clip:text!important;color:transparent!important;-webkit-text-fill-color:transparent!important;text-shadow:0 3px 12px rgba(0,0,0,.38)!important;filter:drop-shadow(0 0 7px rgba(226,168,48,.14))}
.rpp-title-divider{position:absolute!important;z-index:9!important;top:24.8%!important;left:28%!important;width:44%!important;height:3.7%!important;background:url('/assets/premium-v5-divider.webp?v=5') center/contain no-repeat!important;pointer-events:none!important;filter:drop-shadow(0 0 5px rgba(244,197,84,.22))}
#rppCrispCopy .jp{position:absolute!important;top:29.1%!important;left:8%!important;right:8%!important;margin:0!important;color:#e8c467!important;text-shadow:0 2px 12px rgba(0,0,0,.92),0 0 13px rgba(230,172,52,.12)!important}
#rppCrispCopy .rpp-jp-date{display:block!important;font:500 clamp(17px,5.15vw,25px)/1.15 ui-serif,'Yu Mincho','Hiragino Mincho ProN',serif!important;letter-spacing:.08em!important}
#rppCrispCopy .rpp-jp-main{display:block!important;margin-top:2.4%!important;font:500 clamp(23px,7vw,33px)/1.18 ui-serif,'Yu Mincho','Hiragino Mincho ProN',serif!important;letter-spacing:.08em!important}
#rppCrispCopy .goldRule{display:none!important}
#rppCrispCopy .bridge{position:absolute!important;top:55.45%!important;left:9%!important;right:9%!important;margin:0!important;color:#e2be61!important;font:500 clamp(12px,3.55vw,17px)/1.3 ui-serif,'Yu Mincho','Hiragino Mincho ProN',serif!important;letter-spacing:.10em!important;text-shadow:0 2px 12px rgba(0,0,0,.92),0 0 12px rgba(235,177,53,.14)!important}
#rppCrispCopy .bridge:before,#rppCrispCopy .bridge:after{content:'✦';color:#f2ce70;margin:0 .7em;font-size:.78em;text-shadow:0 0 10px rgba(255,211,100,.75)}
#rppCrispCopy .vow{display:none!important}
.rpp-v5-panel{position:absolute;z-index:6;left:7.2%;right:7.2%;top:60.0%;bottom:3.25%;pointer-events:none;background:linear-gradient(180deg,rgba(2,14,34,.76),rgba(1,9,23,.90));border:1px solid rgba(203,145,43,.78);box-shadow:inset 0 0 0 1px rgba(255,225,139,.06),inset 0 0 0 7px rgba(181,120,27,.035),0 16px 40px rgba(0,0,0,.24);clip-path:polygon(4% 0,96% 0,100% 5%,100% 95%,96% 100%,4% 100%,0 95%,0 5%)}
.rpp-v5-panel:before{content:"";position:absolute;inset:2.2%;border:1px solid rgba(226,175,70,.37);clip-path:inherit}
#rppAuthLabel{position:absolute!important;z-index:10!important;top:62.45%!important;left:12%!important;right:12%!important;margin:0!important;text-align:center!important;color:#e0c275!important;font:600 clamp(10px,2.85vw,14px)/1.25 ui-serif,'Yu Mincho',serif!important;letter-spacing:.13em!important;text-shadow:0 2px 10px rgba(0,0,0,.85)!important}
#gate #pw{position:absolute!important;z-index:12!important;left:12.3%!important;top:65.2%!important;width:75.4%!important;height:5.7%!important;margin:0!important;padding:0 5% 0 15%!important;border:0!important;border-radius:999px!important;background:url('/assets/premium-v5-input.webp?v=5') center/100% 100% no-repeat!important;color:#f8ecc9!important;caret-color:#f7d26e!important;font:500 clamp(12px,3.2vw,18px)/1 ui-serif,'Yu Mincho','Hiragino Mincho ProN',serif!important;letter-spacing:.02em!important;box-shadow:0 8px 22px rgba(0,0,0,.23),0 0 20px rgba(217,161,52,.06)!important;outline:none!important;appearance:none!important}
#gate #pw::placeholder{color:rgba(220,218,213,.46)!important}#gate #pw:focus{box-shadow:0 0 0 2px rgba(246,205,104,.26),0 10px 26px rgba(0,0,0,.30),0 0 26px rgba(224,175,62,.12)!important}
.rpp-v5-lock{position:absolute;z-index:13;left:15.0%;top:66.0%;width:5.2%;aspect-ratio:1;background:url('/assets/premium-v5-lock.webp?v=5') center/contain no-repeat;pointer-events:none;filter:drop-shadow(0 0 4px rgba(242,191,71,.23))}
html body #gate #unlock.rpp-action,#gate #unlock{position:absolute!important;z-index:13!important;left:16.6%!important;top:73.15%!important;width:66.8%!important;height:6.75%!important;margin:0!important;padding:0 8%!important;border:0!important;border-radius:0!important;background:url('/assets/premium-v5-unlock.webp?v=5') center/100% 100% no-repeat!important;color:#251604!important;font:700 clamp(16px,4.15vw,22px)/1 ui-serif,'Yu Mincho','Hiragino Mincho ProN',serif!important;letter-spacing:.12em!important;text-shadow:0 1px 0 rgba(255,255,255,.34)!important;box-shadow:0 12px 28px rgba(0,0,0,.28),0 0 25px rgba(230,172,52,.09)!important;filter:none!important;overflow:hidden!important}
#gate #unlock:hover,#gate #unlock:focus-visible{filter:brightness(1.055)!important;box-shadow:0 14px 34px rgba(0,0,0,.34),0 0 34px rgba(236,186,74,.16)!important}
html body #gate #gateAuthorLink.rpp-action,#gate #gateAuthorLink{position:absolute!important;z-index:13!important;left:17.0%!important;top:83.0%!important;width:66%!important;height:7.65%!important;margin:0!important;padding:0!important;border:0!important;border-radius:999px!important;background:url('/assets/premium-v5-author.webp?v=5') center/100% 100% no-repeat!important;color:transparent!important;font-size:0!important;line-height:1!important;text-decoration:none!important;box-shadow:0 10px 27px rgba(0,0,0,.25),0 0 25px rgba(217,163,57,.08)!important;animation:rppV5AuthorGlow 6.2s ease-in-out infinite!important;overflow:hidden!important}
#gate #gateAuthorLink::before{content:'私の記録を綴る'!important;position:absolute!important;display:block!important;left:0!important;right:0!important;top:25%!important;color:#f0d487!important;font:500 clamp(14px,3.65vw,20px)/1.08 ui-serif,'Yu Mincho','Hiragino Mincho ProN',serif!important;letter-spacing:.10em!important;text-align:center!important;text-shadow:0 2px 10px rgba(0,0,0,.75)!important;background:none!important;pointer-events:none!important}
#gate #gateAuthorLink::after{content:'WRITE YOUR STORY'!important;position:absolute!important;display:block!important;left:0!important;right:0!important;top:61%!important;color:#e7bd5a!important;font:600 clamp(7px,2.05vw,11px)/1 Georgia,'Times New Roman',serif!important;letter-spacing:.22em!important;text-align:center!important;text-shadow:0 2px 8px rgba(0,0,0,.7)!important;background:none!important;pointer-events:none!important}
#gate #msg{z-index:15!important;top:71.1%!important}.rpp-crisp-sparkles{z-index:3!important;opacity:.68!important}
@keyframes rppArtworkBreath{0%,100%{transform:scale(1.000)}50%{transform:scale(1.008)}}
@keyframes rppV5AuthorGlow{0%,100%{filter:brightness(1);box-shadow:0 10px 27px rgba(0,0,0,.25),0 0 22px rgba(217,163,57,.06)}50%{filter:brightness(1.025);box-shadow:0 12px 30px rgba(0,0,0,.29),0 0 31px rgba(229,178,66,.13)}}
@media(max-width:600px){#gate .gate-card{width:100vw!important;box-shadow:none!important}#gate:not(.hidden){padding:0!important}}
@media(min-width:900px){#gate:not(.hidden){padding:14px!important}#gate .gate-card{width:min(430px,49.3svh)!important;max-width:430px!important;box-shadow:0 38px 125px rgba(0,0,0,.67),0 0 90px rgba(210,169,71,.09)!important}#rppCrispCopy .rpp-pride{font-size:49px!important}#rppCrispCopy .rpp-road{font-size:24px!important}#rppCrispCopy .rpp-jp-date{font-size:20px!important}#rppCrispCopy .rpp-jp-main{font-size:27px!important}}
@media(prefers-reduced-motion:reduce){#gate .gate-card.orn:before,#gate #gateAuthorLink{animation:none!important}}
</style>
<script>
(()=>{const enhance=()=>{const card=document.querySelector('#gate .gate-card');if(!card)return;card.dataset.artworkVersion='premium-v5-parts';card.dataset.artworkAssets='bg,input,unlock,author,divider,lock';const title=document.querySelector('#rppCrispCopy .title');if(title&&!title.querySelector('.rpp-pride'))title.innerHTML='<span class="rpp-road">ROAD TO</span><span class="rpp-pride">PEACE PRIDE</span>';const jp=document.querySelector('#rppCrispCopy .jp');if(jp&&!jp.querySelector('.rpp-jp-main'))jp.innerHTML='<span class="rpp-jp-date">9.12までの</span><span class="rpp-jp-main">挑戦と誓いの記録</span>';if(!card.querySelector('.rpp-title-divider')){const d=document.createElement('span');d.className='rpp-title-divider';card.appendChild(d)}if(!card.querySelector('.rpp-v5-panel')){const p=document.createElement('span');p.className='rpp-v5-panel';card.appendChild(p)}if(!card.querySelector('.rpp-v5-lock')){const l=document.createElement('span');l.className='rpp-v5-lock';card.appendChild(l)}if(!card.querySelector('.rpp-v5-frame')){const f=document.createElement('span');f.className='rpp-v5-frame';card.appendChild(f);['tl','tr','br','bl'].forEach(k=>{const c=document.createElement('span');c.className='rpp-v5-corner '+k;card.appendChild(c)})}const pw=document.querySelector('#pw');if(pw){pw.autocomplete='current-password';pw.setAttribute('aria-label','閲覧パスワード')}const unlock=document.querySelector('#unlock');if(unlock)unlock.setAttribute('aria-label','記録をひらく');const author=document.querySelector('#gateAuthorLink');if(author)author.setAttribute('aria-label','私の記録を綴る / WRITE YOUR STORY')};enhance();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance,{once:true});setTimeout(enhance,40);setTimeout(enhance,320)})();
</script>`;

function apply(response){return new HTMLRewriter().on('body',{element(el){el.append(PREMIUM_V5,{html:true})}}).transform(response)}
export default {async fetch(request,env,ctx){const response=await app.fetch(request,env,ctx);const type=response.headers.get('content-type')||'';const path=new URL(request.url).pathname.replace(/\/$/,'')||'/';if(type.includes('text/html')&&['/','/index.html'].includes(path)){const transformed=apply(response);const headers=new Headers(transformed.headers);headers.set('cache-control','no-store, no-cache, must-revalidate, max-age=0');headers.set('pragma','no-cache');headers.set('expires','0');return new Response(transformed.body,{status:transformed.status,statusText:transformed.statusText,headers})}return response}};
